apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tourswitch
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: tourswitch-be
            repoURL: https://github.com/green-tour/tourswitch-BE.git
            path: k8s
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: tourswitch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
